name: Go

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  release:
    name: Create Release
    if: "startsWith(github.event.head_commit.message, 'v')"
    runs-on: "ubuntu-latest"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Generate build files
        uses: thatisuday/go-cross-build@v1
        with:
            platforms: 'linux/amd64, darwin/amd64, windows/amd64'
            package: 'go'
            name: 'ledfx'
            compress: 'false'
            dest: 'dist'
      - name: Release Notes
        run: git log $(git describe HEAD~ --tags --abbrev=0)..HEAD --pretty='format:* %h %s%n  * by %an' --no-merges >> ".github/RELEASE-TEMPLATE.md"
      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{github.event.head_commit.message}}',
              sha: context.sha
            })
      - name: Release with Notes
        if: always()
        uses: softprops/action-gh-release@v1
        with:
          body_path: ".github/RELEASE-TEMPLATE.md"
          tag_name: ${{github.event.head_commit.message}}
          draft: true
          files: |
            dist/ledfx-go-windows-amd64.exe
            dist/ledfx-go-linux-amd64
            dist/ledfx-go-darvin-amd64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
